### ISSUE TITLE
Error's in console chat

### ISSUE THREAD

**Issue by dmodoomsirius** [TheBusyBiscuit/QuickMarket#10]
## Description (Required)

Error happens when attempting to create a shop when i have * perms with pex.
## Steps to reproduce the Issue (Required)

1. put down sign
2. attempt to create shop
3. get error's in console

## Server Log / Error Report

https://gist.github.com/dmodoomsirius/f15deba99ad95234bbc31b3bad7d3c09

## Environment (Required)

 - Minecraft Version: 1.14.4
 - CS-CoreLib Version: v1.6.1
 - QuickMarket Version:v1.3

**Comment by TheBusyBiscuit** [comment]
Unable to reproduce this Issue.
