### ISSUE TITLE
movable item / hologram

### ISSUE THREAD

**Issue by J3fftw1** [TheBusyBiscuit/QuickMarket#17]
## Description (Required)
When you place a block above the chest shop it moves the hologram and item when you leave the item / hologram alone for long enough it teleports back

might be better to disable the hologram and item when there is a block above so you can make stackable shops

## Steps to reproduce the Issue (Required)
https://streamable.com/qb0bm

## Expected behavior (Required)
that the hologram stays and the item to

## Environment (Required)

 - Minecraft Version: 1.14.4
 - CS-CoreLib Version: 76
 - QuickMarket Version: 21

**Comment by TheBusyBiscuit** [comment]
That is not a bug...
Just don't place a block above it.
Removing the Item makes no sense, people wouldn't know what to buy/sell without it...
