### ISSUE TITLE
Error Once Shop Created

### ISSUE THREAD

**Issue by Mabit100** [TheBusyBiscuit/QuickMarket#2]
## Description (Required)
Created a shop, worked perfectly, hologram showing item, price set and item was registered correctly on the sign and on the hologram. 
When trying to click the sign to sell an item error was thrown. (https://pastebin.com/tX7rxd3W)

This is happening wither or not its a Slimefun item or a Normal MC item. 

It seems to be stuck in editing mode. As you can see from screenshot 2 when a player tries to use the shop is says Shop is currently being edited.

![image](https://user-images.githubusercontent.com/21134218/59148578-aab3f980-8a02-11e9-9c84-a22ecc6f9394.png)

![image](https://user-images.githubusercontent.com/21134218/59148575-a2f45500-8a02-11e9-961f-0138cc5d5303.png)

## Steps to reproduce the Issue (Required)
https://ibb.co/9bK3pNJ

## Expected behavior (Required)
Item to be removed from player inventory and money given.

## Server Log / Error Report
https://pastebin.com/tX7rxd3W

## Environment (Required)

 - Minecraft Version: V1.14.2 R0.1.20190527
 - CS-CoreLib Version: CS-CoreLib-51.jar
 - QuickMarket Version: QuickMarket-3.jar
- Slimefun Version: Slimefun4-106.jar

**Comment by TheBusyBiscuit** [comment]
According to the Error you posted, you apparently managed to set the item to "nothing".
That is pretty much impossible to happen.

But I went ahead and updated it to throw a more clearer exception when this happens in the future.
(Won't fix any existing shops though)

**Comment by Mabit100** [comment]
OK thanks, will update and run and see what happens.

**Comment by Mabit100** [comment]
Was working perfectly, several players testing and all able to make shops, buy and sell both normal and slimefun items.
When we started deleting shops we had a few errors. Players can delete their own shops but if I as OP try to delete then this error occurs and the message below.

https://pastebin.com/5Y15fkau


![image](https://user-images.githubusercontent.com/21134218/59150405-c1fee100-8a1a-11e9-9c71-b92befb7f06b.png)

Minecraft Version: V1.14.2 R0.1.20190527
CS-CoreLib Version: CS-CoreLib-51.jar
QuickMarket Version: QuickMarket-4.jar
Slimefun Version: Slimefun4-106.jar
