### ISSUE TITLE
Cannot create shops.

### ISSUE THREAD

**Issue by TarikBerk** [TheBusyBiscuit/QuickMarket#5]
## Description (Required)
Cannot create any shop.

## Steps to reproduce the Issue (Required)
1. Put a chest.
2. Place a sign on it.
3. Type the following:
[shop]
1
10
sell

## Expected behavior (Required)
Shop to be created.

## Server Log / Error Report
https://pastebin.com/QvnjfD65

## Environment (Required)
 - Minecraft Version: 1.13.2 (Paper 1.13.2 Build #632)
 - CS-CoreLib Version: Not using it. Still happens when using it anyway, but it isn't listed as required on the dev page.
 - QuickMarket Version: v1.3 (https://dev.bukkit.org/projects/quickmarket/files/2725123)

**Comment by TheBusyBiscuit** [comment]
Should be fixed in QuickMarket build 11.
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/QuickMarket/master/
