### ISSUE TITLE
Shop GUI Not Working

### ISSUE THREAD

**Issue by Mabit100** [TheBusyBiscuit/QuickMarket#6]
## Description (Required)
One you create a shop the GUI stops working and can drag the items out the GUI and no changes are made. You cannot change the item to be sold. Cannot delete the shop since the delete symbol comes out the GUI.

## Steps to reproduce the Issue (Required)
![image](https://user-images.githubusercontent.com/21134218/59976990-b0453e00-95c3-11e9-97fe-40b564533568.png)

## Expected behavior (Required)
See above

## Server Log / Error Report
https://pastebin.com/9YGFNrW3

## Environment (Required)

 - Minecraft Version: 1.14.2
 - CS-CoreLib Version: 61
 - QuickMarket Version: 11

**Comment by Mabit100** [comment]
This is the same behaviour on 1.14.3 same corelib and quickmarket version

**Comment by eywoanman** [comment]
So I do... Im 1.13.2

**Comment by TheBusyBiscuit** [comment]
Should be fixed in Build 12
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/QuickMarket/master/
Can someone confirm this?

**Comment by Mabit100** [comment]
Its working, can now make shops, however, you cannot sell slimefun items. Do you want that as a new ticket. You can sell slimefun items on version 4
